# Site settings
title: SAHKI Abdelmadjid portfolio
description: Bienvenu sur mon portfolio, je suis Abdelmadjid SAHKI, ingénieur logiciel.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Abdelmadjid SAHKI
user_description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
user_title: Software engineer
email: sahki@intechinfo.fr
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-167858043-1"

exclude: ['package.json', 'src' , 'node_modules']
