# Site settings
title: SAHKI Abdelmadjid portfolio
description: Bienvenu sur mon portfolio, je suis Abdelmadjid SAHKI, ingénieur logiciel.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Abdelmadjid SAHKI
user_description: Passionné par les futurs techniques je me suis orienté vers un master en ingénierie logicielle. Fort de mes 2 années d'alternance, j’ai pu rapidement m'insérer dans le monde professionnel bien différent des bancs de l'école, j'ai également une bonne sensibilité à la gestion de projets agiles. N'hésitez pas à me contacter pour plus de renseignements.
user_title: Software engineer
email: sahki@intechinfo.fr
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-167858043-1"

exclude: ['package.json', 'src' , 'node_modules']
